"""
Extract and analyze class labels for Model1 (Rice and Potato)
"""
import os
import tensorflow as tf
from tensorflow import keras
import json
import numpy as np

def extract_model1_labels():
    """
    Extract class labels from Model1 (Rice and Potato)
    """
    print("\n" + "="*70)
    print("MODEL 1 (RICE AND POTATO) - CLASS LABEL EXTRACTION")
    print("="*70)
    
    # Path to model
    models_dir = os.path.join(os.path.dirname(__file__), 'models')
    model1_path = os.path.join(models_dir, 'Model1(Rice and Potato).h5')
    
    if not os.path.exists(model1_path):
        print(f"[ERROR] Model not found: {model1_path}")
        return None
    
    try:
        # Load model
        print("\n[1] Loading Model1...")
        model = keras.models.load_model(model1_path, compile=False)
        print("[OK] Model loaded successfully")
        
        # Get model information
        print("\n[2] Analyzing Model Architecture...")
        input_shape = model.input_shape
        output_shape = model.output_shape
        num_classes = output_shape[1] if len(output_shape) == 2 else None
        
        print(f"    Input Shape: {input_shape}")
        print(f"    Output Shape: {output_shape}")
        print(f"    Number of Classes: {num_classes}")
        print(f"    Image Size: {input_shape[1]}x{input_shape[2]}")
        print(f"    Total Layers: {len(model.layers)}")
        
        # Model summary (first and last few layers)
        print("\n[3] Model Architecture (First and Last Layers):")
        print(f"    First 3 layers:")
        for i, layer in enumerate(model.layers[:3]):
            print(f"      {i+1}. {layer.name} ({layer.__class__.__name__})")
        
        print(f"    ...")
        print(f"    Last 3 layers:")
        for i, layer in enumerate(model.layers[-3:], start=len(model.layers)-2):
            print(f"      {i}. {layer.name} ({layer.__class__.__name__})")
        
        # Generate class labels
        print("\n[4] Class Labels:")
        print("-" * 70)
        
        # Read existing labels from class_labels.json
        labels_path = os.path.join(models_dir, 'class_labels.json')
        if os.path.exists(labels_path):
            with open(labels_path, 'r') as f:
                all_labels = json.load(f)
                model1_labels = all_labels.get('rice_potato', [])
            
            print(f"\n    Found {len(model1_labels)} labels in class_labels.json:")
            print(f"    Expected: {num_classes} classes\n")
            
            if len(model1_labels) == num_classes:
                print("    [OK] Label count matches model output!")
            else:
                print(f"    [WARNING] Label count mismatch!")
                print(f"      Expected: {num_classes}")
                print(f"      Found: {len(model1_labels)}")
            
            print("\n    Class Labels (Index -> Disease Name):")
            print("    " + "-" * 66)
            for idx, label in enumerate(model1_labels):
                # Parse disease info
                if '_' in label:
                    parts = label.split('_')
                    crop = parts[0]
                    disease = ' '.join(parts[1:])
                else:
                    crop = "General"
                    disease = label
                
                print(f"    [{idx:2d}]  {label:35s}  ({crop} - {disease})")
            
            print("\n" + "="*70)
            print("CLASS LABELS SUMMARY")
            print("="*70)
            
            # Count by crop
            rice_count = sum(1 for label in model1_labels if label.startswith('Rice_') or label == 'Healthy')
            potato_count = sum(1 for label in model1_labels if label.startswith('Potato_'))
            
            print(f"\n  Rice diseases: {rice_count}")
            print(f"  Potato diseases: {potato_count}")
            print(f"  Total: {len(model1_labels)}")
            
            # Create formatted output for code
            print("\n" + "="*70)
            print("PYTHON CODE FORMAT (for use in your application)")
            print("="*70)
            print("\nMODEL1_CLASS_LABELS = [")
            for idx, label in enumerate(model1_labels):
                comma = "," if idx < len(model1_labels) - 1 else ""
                print(f'    "{label}"{comma}  # Class {idx}')
            print("]")
            
            # Save to a separate file
            output_file = os.path.join(models_dir, 'model1_class_labels.py')
            with open(output_file, 'w') as f:
                f.write('"""\n')
                f.write('Class labels for Model1 (Rice and Potato)\n')
                f.write('Auto-generated by extract_model1_labels.py\n')
                f.write('"""\n\n')
                f.write('MODEL1_CLASS_LABELS = [\n')
                for idx, label in enumerate(model1_labels):
                    comma = "," if idx < len(model1_labels) - 1 else ""
                    f.write(f'    "{label}"{comma}  # Class {idx}\n')
                f.write(']\n\n')
                f.write('# Crop groups\n')
                f.write('RICE_LABELS = [label for label in MODEL1_CLASS_LABELS if label.startswith("Rice_") or label == "Healthy"]\n')
                f.write('POTATO_LABELS = [label for label in MODEL1_CLASS_LABELS if label.startswith("Potato_")]\n')
            
            print(f"\n[OK] Class labels saved to: {output_file}")
            
            return model1_labels
        else:
            print(f"[ERROR] class_labels.json not found at {labels_path}")
            return None
            
    except Exception as e:
        print(f"[ERROR] Failed to extract labels: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

if __name__ == '__main__':
    labels = extract_model1_labels()
    
    if labels:
        print("\n" + "="*70)
        print("[SUCCESS] Class labels extracted and saved!")
        print("="*70)
    else:
        print("\n" + "="*70)
        print("[FAILED] Could not extract class labels")
        print("="*70)
